etcd:
  image: quay.io/coreos/etcd:v2.2.0
  command: >
    -listen-client-urls http://0.0.0.0:2379
    -advertise-client-urls http://etcd:2379
  ports:
    - 2379:2379

squirrel-master:
  build: squirrel-master/
  environment:
    SQUIRREL_ENDPOINT: http://etcd:2379
  links:
    - etcd:etcd
  privileged: true
  ports:
    - 9999:9999
    - 1234:1234

squirrel-worker:
  build: squirrel-worker/
  environment:
    ETCDCTL_API: 3
    SQUIRREL_ENDPOINT: http://etcd:2379
  links:
    - squirrel-master:squirrel-master
    - etcd:etcd
  privileged: true
