FROM ubuntu

MAINTAINER Vladimir Atanasov

COPY squirrel-master /tmp/squirrel-master
RUN chmod +x /tmp/squirrel-master

COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh

ENTRYPOINT ["/tmp/entrypoint.sh"]
